docs_dir: notes
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 # Sun icon
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4 # Moon icon
        name: Switch to light mode
  custom_dir: .custom_theme/
site_name: Agorist Notes
plugins: []
markdown_extensions:
  - meta
nav:
  - 'Home': 'index.md'
  - 'Christmas': 'the_legend_of_anarcho_claus.md'
  - 'Agora': 'an_agorist_primer.md'
  - '[Draft] Lunch': 'lunch-v0.2.0.md'
