docs_dir: notes
theme:
  name: gitbook
  custom_dir: .custom_theme/
site_name: Agorist Notes
plugins: []
markdown_extensions:
  - meta
nav:
  - 'Home': 'index.md'
  - 'Christmas': 'the_legend_of_anarcho_claus.md'
  - 'Agora': 'an_agorist_primer.md'
  - '[Draft] Lunch': 'lunch-v0.1.1.md'
